"""Portfolio Optimisation Engine for the NEPSE Quant Engine.

Constructs optimal portfolios from BUY recommendations generated by
the :class:`~src.recommendations.engine.RecommendationEngine`.

Integrates with:

- :class:`~src.recommendations.engine.RecommendationEngine`
- :class:`~src.risk.engine.RiskEngine`
- :class:`~src.portfolio.allocator.PortfolioAllocator`
- :class:`~src.simulation.monte_carlo.MonteCarloSimulator`
- :class:`~src.analytics.performance.PerformanceAnalyzer`
- :class:`~src.optimization.walk_forward.WalkForwardOptimizer`
- :class:`~src.optimization.parameter_optimizer.ParameterOptimizer`

without modifying any of their public APIs.

Supports six optimisation methods:

1. **Equal Weight** — distribute capital equally among all positions.
2. **Maximum Sharpe** — maximise the risk-adjusted return.
3. **Minimum Variance** — minimise portfolio volatility.
4. **Risk Parity** — equal risk contribution from each position.
5. **Score Weighted** — weights proportional to recommendation score.
6. **Confidence Weighted** — weights proportional to confidence.

Designed for future extensibility with Black-Litterman, Hierarchical
Risk Parity, Mean-CVaR, Equal Risk Contribution, and Kelly portfolio
optimisation methods.
"""

from __future__ import annotations

import csv
import math
from dataclasses import dataclass, field
from typing import Any

from src.logging.logger import logger

try:
    import numpy as np

    _HAS_NUMPY = True
except ImportError:  # pragma: no cover
    _HAS_NUMPY = False

try:
    from scipy.optimize import minimize as _scipy_minimize

    _HAS_SCIPY = True
except ImportError:  # pragma: no cover
    _HAS_SCIPY = False


# ======================================================================
# Constants
# ======================================================================

_VALID_METHODS = frozenset(
    {
        "equal_weight",
        "max_sharpe",
        "min_variance",
        "risk_parity",
        "score_weighted",
        "confidence_weighted",
    }
)

_SECTOR_CATEGORIES: list[str] = [
    "Banking",
    "Hydropower",
    "Finance",
    "Insurance",
    "Hotels",
    "Manufacturing",
    "Others",
]

_DEFAULT_CORRELATION = 0.15  # default pairwise correlation when none given
_MAX_POSITIONS_DEFAULT = 50
_MIN_CONFIDENCE_DEFAULT = 0.0
_MIN_SCORE_DEFAULT = 0.0

# scipy SLSQP convergence tolerances
_SCIPY_TOL = 1e-8
_SCIPY_MAXITER = 1000


# ======================================================================
# PortfolioAllocation — per-position output dataclass
# ======================================================================


@dataclass
class PortfolioAllocation:
    """A single position allocation within an optimised portfolio.

    Attributes:
        symbol:
            Stock ticker symbol.
        weight:
            Portfolio weight allocated to this position (0–1).
        shares:
            Whole number of shares to purchase (always rounded down).
        capital:
            Rupee amount allocated to this position.
        expected_return:
            Expected return for this position (fraction, e.g. 0.05 = 5%).
        risk:
            Risk (standard deviation of returns) for this position.
        sector:
            Sector classification of the stock.
    """

    symbol: str
    weight: float
    shares: int
    capital: float
    expected_return: float
    risk: float
    sector: str = "Others"

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable dictionary representation.

        Returns:
            Dictionary with all allocation fields.
        """
        return {
            "symbol": self.symbol,
            "weight": round(self.weight, 6),
            "shares": self.shares,
            "capital": round(self.capital, 2),
            "expected_return": round(self.expected_return, 6),
            "risk": round(self.risk, 6),
            "sector": self.sector,
        }


# ======================================================================
# PortfolioOptimizationResult — full-optimisation output dataclass
# ======================================================================


@dataclass
class PortfolioOptimizationResult:
    """Complete result of a single portfolio optimisation run.

    Attributes:
        method:
            The optimisation method used (e.g. ``"equal_weight"``).
        expected_return:
            Expected portfolio return (fraction).
        portfolio_risk:
            Portfolio volatility / risk (standard deviation, fraction).
        sharpe_ratio:
            Sharpe ratio of the optimised portfolio.
        diversification_score:
            Diversification score (0–1). Higher is more diversified.
        capital_used:
            Total capital deployed across all positions.
        cash_remaining:
            Capital not allocated.
        allocations:
            List of :class:`PortfolioAllocation` instances.
        weights:
            Dictionary mapping symbol to weight.
        sector_exposure:
            Dictionary mapping sector name to total allocation.
        summary:
            Human-readable summary string.
        constraint_violations:
            List of constraint violation messages (empty if none).
    """

    method: str
    expected_return: float = 0.0
    portfolio_risk: float = 0.0
    sharpe_ratio: float = 0.0
    diversification_score: float = 0.0
    capital_used: float = 0.0
    cash_remaining: float = 0.0
    allocations: list[PortfolioAllocation] = field(default_factory=list)
    weights: dict[str, float] = field(default_factory=dict)
    sector_exposure: dict[str, float] = field(default_factory=dict)
    summary: str = ""
    constraint_violations: list[str] = field(default_factory=list)

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable dictionary representation.

        Returns:
            Dictionary with all optimisation result fields.
        """
        return {
            "method": self.method,
            "expected_return": round(self.expected_return, 6),
            "portfolio_risk": round(self.portfolio_risk, 6),
            "sharpe_ratio": round(self.sharpe_ratio, 4),
            "diversification_score": round(self.diversification_score, 4),
            "capital_used": round(self.capital_used, 2),
            "cash_remaining": round(self.cash_remaining, 2),
            "allocations": [a.to_dict() for a in self.allocations],
            "weights": {
                k: round(v, 6) for k, v in self.weights.items()
            },
            "sector_exposure": {
                k: round(v, 4) for k, v in self.sector_exposure.items()
            },
            "summary": self.summary,
            "constraint_violations": list(self.constraint_violations),
        }

    # ------------------------------------------------------------------
    # Export
    # ------------------------------------------------------------------

    def export_csv(self, path: str) -> None:
        """Export allocations to a CSV file.

        Writes one row per position with symbol, weight, shares,
        capital, expected_return, risk, and sector columns.

        Args:
            path: File path for the CSV output.

        Raises:
            OSError: If the file cannot be written.
        """
        fieldnames = [
            "symbol",
            "weight",
            "shares",
            "capital",
            "expected_return",
            "risk",
            "sector",
        ]
        with open(path, mode="w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            for alloc in self.allocations:
                writer.writerow(alloc.to_dict())

        logger.info(
            "Exported %d allocations to '%s'.",
            len(self.allocations),
            path,
        )


# ======================================================================
# PortfolioOptimizer
# ======================================================================


class PortfolioOptimizer:
    """Construct optimal portfolios from a set of BUY recommendations.

    The optimiser converts raw recommendations (from the
    :class:`~src.recommendations.engine.RecommendationEngine`) into
    concrete position-level capital allocations using one of six
    supported optimisation methods.

    All monetary values are in NPR.

    Args:
        capital:
            Total investable capital in NPR (must be > 0).
        risk_free_rate:
            Risk-free rate as a decimal fraction (e.g. 0.05 = 5%).
            Defaults to ``0.0``.
        max_position_weight:
            Maximum allowed weight for any single position, as a decimal
            fraction (must be in ``(0, 1]``).  Defaults to ``0.25``.
        min_position_weight:
            Minimum allowed weight for any single position, as a decimal
            fraction (must be in ``[0, 1)``).  Defaults to ``0.0``.
        sector_limit:
            Maximum exposure to any single sector, as a decimal fraction
            (must be in ``(0, 1]``).  Defaults to ``0.40``.

    Raises:
        ValueError: If any parameter violates its constraints.
    """

    def __init__(
        self,
        capital: float,
        risk_free_rate: float = 0.0,
        max_position_weight: float = 0.25,
        min_position_weight: float = 0.0,
        sector_limit: float = 0.40,
    ) -> None:
        if capital <= 0:
            raise ValueError(
                f"Capital must be positive, got {capital}."
            )

        if risk_free_rate < 0 or risk_free_rate >= 1:
            raise ValueError(
                f"risk_free_rate must be in [0, 1), got {risk_free_rate}."
            )

        if not 0 < max_position_weight <= 1:
            raise ValueError(
                f"max_position_weight must be in (0, 1], "
                f"got {max_position_weight}."
            )

        if not 0 <= min_position_weight < 1:
            raise ValueError(
                f"min_position_weight must be in [0, 1), "
                f"got {min_position_weight}."
            )

        if min_position_weight > max_position_weight:
            raise ValueError(
                f"min_position_weight ({min_position_weight}) must not "
                f"exceed max_position_weight ({max_position_weight})."
            )

        if not 0 < sector_limit <= 1:
            raise ValueError(
                f"sector_limit must be in (0, 1], got {sector_limit}."
            )

        self._capital = capital
        self._risk_free_rate = risk_free_rate
        self._max_weight = max_position_weight
        self._min_weight = min_position_weight
        self._sector_limit = sector_limit

        logger.debug(
            "PortfolioOptimizer(capital=%.2f, risk_free_rate=%.4f, "
            "max_weight=%.4f, min_weight=%.4f, sector_limit=%.4f)",
            capital,
            risk_free_rate,
            max_position_weight,
            min_position_weight,
            sector_limit,
        )

    # ==================================================================
    # Public optimisation methods
    # ==================================================================

    def optimize_equal_weight(
        self,
        recommendations: list[dict[str, Any]],
        correlation_matrix: list[list[float]] | None = None,
        max_positions: int = _MAX_POSITIONS_DEFAULT,
        min_confidence: float = _MIN_CONFIDENCE_DEFAULT,
        min_score: float = _MIN_SCORE_DEFAULT,
    ) -> PortfolioOptimizationResult:
        """Allocate capital equally across all qualifying recommendations.

        Each qualifying position receives an equal weight of ``1 / N``,
        where ``N`` is the number of qualifying recommendations.

        Args:
            recommendations:
                List of recommendation dicts.  Each must contain at
                least ``symbol``.  May include ``confidence``,
                ``score``, ``expected_return``, ``risk``, ``sector``.
            correlation_matrix:
                Optional NxN correlation matrix.  If provided, used for
                portfolio variance and diversification calculations.
            max_positions:
                Maximum number of positions to include.  Defaults to 50.
            min_confidence:
                Minimum confidence threshold (0–100).  Positions with
                confidence below this are excluded.
            min_score:
                Minimum score threshold.  Positions with score below
                this are excluded.

        Returns:
            A :class:`PortfolioOptimizationResult` with equal-weight
            allocations.

        Raises:
            ValueError: If no recommendations pass filtering.
        """
        return self._optimize(
            method="equal_weight",
            recommendations=recommendations,
            correlation_matrix=correlation_matrix,
            max_positions=max_positions,
            min_confidence=min_confidence,
            min_score=min_score,
        )

    def optimize_max_sharpe(
        self,
        recommendations: list[dict[str, Any]],
        correlation_matrix: list[list[float]] | None = None,
        max_positions: int = _MAX_POSITIONS_DEFAULT,
        min_confidence: float = _MIN_CONFIDENCE_DEFAULT,
        min_score: float = _MIN_SCORE_DEFAULT,
    ) -> PortfolioOptimizationResult:
        """Maximise the Sharpe ratio of the portfolio.

        Uses numerical optimisation (scipy SLSQP) to find the weight
        vector that maximises ``(expected_return - risk_free_rate) /
        portfolio_risk``, subject to position and sector constraints.

        Falls back to equal-weight if scipy is unavailable.

        Args:
            recommendations:
                List of recommendation dicts.
            correlation_matrix:
                Optional NxN correlation matrix.
            max_positions:
                Maximum number of positions.
            min_confidence:
                Minimum confidence threshold (0–100).
            min_score:
                Minimum score threshold.

        Returns:
            A :class:`PortfolioOptimizationResult` with max-Sharpe
            allocations.

        Raises:
            ValueError: If no recommendations pass filtering.
        """
        return self._optimize(
            method="max_sharpe",
            recommendations=recommendations,
            correlation_matrix=correlation_matrix,
            max_positions=max_positions,
            min_confidence=min_confidence,
            min_score=min_score,
        )

    def optimize_min_variance(
        self,
        recommendations: list[dict[str, Any]],
        correlation_matrix: list[list[float]] | None = None,
        max_positions: int = _MAX_POSITIONS_DEFAULT,
        min_confidence: float = _MIN_CONFIDENCE_DEFAULT,
        min_score: float = _MIN_SCORE_DEFAULT,
    ) -> PortfolioOptimizationResult:
        """Minimise the portfolio variance (volatility).

        Uses numerical optimisation (scipy SLSQP) to find the weight
        vector that minimises portfolio variance, subject to position
        and sector constraints.

        Falls back to equal-weight if scipy is unavailable.

        Args:
            recommendations:
                List of recommendation dicts.
            correlation_matrix:
                Optional NxN correlation matrix.
            max_positions:
                Maximum number of positions.
            min_confidence:
                Minimum confidence threshold (0–100).
            min_score:
                Minimum score threshold.

        Returns:
            A :class:`PortfolioOptimizationResult` with min-variance
            allocations.

        Raises:
            ValueError: If no recommendations pass filtering.
        """
        return self._optimize(
            method="min_variance",
            recommendations=recommendations,
            correlation_matrix=correlation_matrix,
            max_positions=max_positions,
            min_confidence=min_confidence,
            min_score=min_score,
        )

    def optimize_risk_parity(
        self,
        recommendations: list[dict[str, Any]],
        correlation_matrix: list[list[float]] | None = None,
        max_positions: int = _MAX_POSITIONS_DEFAULT,
        min_confidence: float = _MIN_CONFIDENCE_DEFAULT,
        min_score: float = _MIN_SCORE_DEFAULT,
    ) -> PortfolioOptimizationResult:
        """Allocate so that each position contributes equal risk.

        Uses an iterative risk-parity algorithm that equalises the
        marginal risk contribution of each position.

        Args:
            recommendations:
                List of recommendation dicts.
            correlation_matrix:
                Optional NxN correlation matrix.
            max_positions:
                Maximum number of positions.
            min_confidence:
                Minimum confidence threshold (0–100).
            min_score:
                Minimum score threshold.

        Returns:
            A :class:`PortfolioOptimizationResult` with risk-parity
            allocations.

        Raises:
            ValueError: If no recommendations pass filtering.
        """
        return self._optimize(
            method="risk_parity",
            recommendations=recommendations,
            correlation_matrix=correlation_matrix,
            max_positions=max_positions,
            min_confidence=min_confidence,
            min_score=min_score,
        )

    def optimize_score_weighted(
        self,
        recommendations: list[dict[str, Any]],
        correlation_matrix: list[list[float]] | None = None,
        max_positions: int = _MAX_POSITIONS_DEFAULT,
        min_confidence: float = _MIN_CONFIDENCE_DEFAULT,
        min_score: float = _MIN_SCORE_DEFAULT,
    ) -> PortfolioOptimizationResult:
        """Allocate weights proportional to each recommendation's score.

        Higher-scored positions receive a larger allocation.

        Args:
            recommendations:
                List of recommendation dicts.
            correlation_matrix:
                Optional NxN correlation matrix.
            max_positions:
                Maximum number of positions.
            min_confidence:
                Minimum confidence threshold (0–100).
            min_score:
                Minimum score threshold.

        Returns:
            A :class:`PortfolioOptimizationResult` with score-weighted
            allocations.

        Raises:
            ValueError: If no recommendations pass filtering.
        """
        return self._optimize(
            method="score_weighted",
            recommendations=recommendations,
            correlation_matrix=correlation_matrix,
            max_positions=max_positions,
            min_confidence=min_confidence,
            min_score=min_score,
        )

    def optimize_confidence_weighted(
        self,
        recommendations: list[dict[str, Any]],
        correlation_matrix: list[list[float]] | None = None,
        max_positions: int = _MAX_POSITIONS_DEFAULT,
        min_confidence: float = _MIN_CONFIDENCE_DEFAULT,
        min_score: float = _MIN_SCORE_DEFAULT,
    ) -> PortfolioOptimizationResult:
        """Allocate weights proportional to each recommendation's confidence.

        Higher-confidence positions receive a larger allocation.

        Args:
            recommendations:
                List of recommendation dicts.
            correlation_matrix:
                Optional NxN correlation matrix.
            max_positions:
                Maximum number of positions.
            min_confidence:
                Minimum confidence threshold (0–100).
            min_score:
                Minimum score threshold.

        Returns:
            A :class:`PortfolioOptimizationResult` with
            confidence-weighted allocations.

        Raises:
            ValueError: If no recommendations pass filtering.
        """
        return self._optimize(
            method="confidence_weighted",
            recommendations=recommendations,
            correlation_matrix=correlation_matrix,
            max_positions=max_positions,
            min_confidence=min_confidence,
            min_score=min_score,
        )

    # ==================================================================
    # Summary
    # ==================================================================

    def summary(
        self,
        result: PortfolioOptimizationResult,
    ) -> dict[str, Any]:
        """Return a concise summary of an optimisation result.

        Args:
            result: A :class:`PortfolioOptimizationResult` instance.

        Returns:
            Dictionary with key portfolio metrics.
        """
        num_positions = len(result.allocations)
        capital_used = result.capital_used
        cash_remaining = self._capital - capital_used

        weights = [a.weight for a in result.allocations]
        avg_position = (
            (capital_used / num_positions) if num_positions else 0.0
        )
        largest_position = max(weights) if weights else 0.0
        smallest_position = min(weights) if weights else 0.0

        return {
            "method": result.method,
            "expected_return": round(result.expected_return, 4),
            "portfolio_volatility": round(result.portfolio_risk, 4),
            "sharpe_ratio": round(result.sharpe_ratio, 4),
            "diversification_score": round(
                result.diversification_score, 4
            ),
            "positions": num_positions,
            "capital_used": round(capital_used, 2),
            "cash_remaining": round(cash_remaining, 2),
            "average_position_size": round(avg_position, 2),
            "largest_position_weight": round(largest_position, 4),
            "smallest_position_weight": round(smallest_position, 4),
            "largest_holding": (
                max(
                    result.allocations,
                    key=lambda a: a.weight,
                ).symbol
                if result.allocations
                else None
            ),
            "sector_allocation": {
                k: round(v, 4)
                for k, v in result.sector_exposure.items()
            },
        }

    # ==================================================================
    # Internal — unified optimisation dispatcher
    # ==================================================================

    def _optimize(
        self,
        method: str,
        recommendations: list[dict[str, Any]],
        correlation_matrix: list[list[float]] | None = None,
        max_positions: int = _MAX_POSITIONS_DEFAULT,
        min_confidence: float = _MIN_CONFIDENCE_DEFAULT,
        min_score: float = _MIN_SCORE_DEFAULT,
    ) -> PortfolioOptimizationResult:
        """Unified optimisation dispatcher.

        Validates inputs, filters recommendations, dispatches to the
        appropriate method, builds allocations, computes portfolio
        metrics, and returns the result.

        Args:
            method: Optimisation method name.
            recommendations: List of recommendation dicts.
            correlation_matrix: Optional correlation matrix.
            max_positions: Max positions to include.
            min_confidence: Min confidence threshold.
            min_score: Min score threshold.

        Returns:
            PortfolioOptimizationResult with the optimised portfolio.

        Raises:
            ValueError: For invalid inputs or empty filtered list.
        """
        # ---- Validate method ----
        if method not in _VALID_METHODS:
            raise ValueError(
                f"Unknown optimisation method '{method}'. "
                f"Valid methods: {sorted(_VALID_METHODS)}"
            )

        # ---- Validate recommendations ----
        if not recommendations:
            raise ValueError(
                "Cannot optimise an empty recommendation list."
            )

        if not isinstance(recommendations, list):
            raise ValueError(
                "recommendations must be a list, "
                f"got {type(recommendations).__name__}."
            )

        logger.info(
            "Optimisation started: method=%s, recommendations=%d",
            method,
            len(recommendations),
        )

        # ---- Filter recommendations ----
        filtered = self._filter_recommendations(
            recommendations=recommendations,
            max_positions=max_positions,
            min_confidence=min_confidence,
            min_score=min_score,
        )

        if not filtered:
            raise ValueError(
                "No recommendations pass the filtering criteria "
                f"(max_positions={max_positions}, "
                f"min_confidence={min_confidence}, "
                f"min_score={min_score})."
            )

        logger.info(
            "Method=%s: %d recommendations after filtering.",
            method,
            len(filtered),
        )

        # ---- Validate correlation matrix ----
        self._validate_correlation_matrix(
            correlation_matrix, len(filtered)
        )

        # ---- Extract arrays ----
        symbols = [r["symbol"] for r in filtered]
        expected_returns = [
            float(r.get("expected_return", 0.0)) for r in filtered
        ]
        risks = [float(r.get("risk", 0.0)) for r in filtered]
        sectors = [str(r.get("sector", "Others")) for r in filtered]
        scores = [float(r.get("score", 0.0)) for r in filtered]
        confidences = [
            float(r.get("confidence", 0.0)) for r in filtered
        ]

        # ---- Compute raw weights by method ----
        raw_weights = self._compute_weights(
            method=method,
            expected_returns=expected_returns,
            risks=risks,
            scores=scores,
            confidences=confidences,
            correlation_matrix=correlation_matrix,
        )

        # ---- Apply constraints ----
        constrained_weights = self._apply_constraints(
            weights=raw_weights,
            sectors=sectors,
        )

        # ---- Rebuild final weights after constraint enforcement ----
        # Only re-normalise when constrained weights exceed 100 %.
        # When max_position_weight limits push total below 1.0 the
        # remainder stays as cash rather than being re-leveraged.
        cw_sum = sum(constrained_weights)
        if cw_sum > 1.0:
            final_weights = [w / cw_sum for w in constrained_weights]
        else:
            final_weights = constrained_weights

        # ---- Check sector limits ----
        violations = self._check_sector_limits(
            weights=final_weights,
            sectors=sectors,
            symbols=symbols,
        )

        # ---- Build allocations ----
        prices = [
            float(r.get("price", 0.0)) for r in filtered
        ]
        allocations = self._build_allocations(
            symbols=symbols,
            weights=final_weights,
            expected_returns=expected_returns,
            risks=risks,
            sectors=sectors,
            prices=prices,
        )

        # ---- Compute portfolio metrics ----
        portfolio_return = self._portfolio_return(
            final_weights, expected_returns
        )
        portfolio_variance = self._portfolio_variance(
            weights=final_weights,
            risks=risks,
            correlation_matrix=correlation_matrix,
        )
        portfolio_vol = math.sqrt(portfolio_variance)
        sharpe = self._sharpe_ratio(portfolio_return, portfolio_vol)
        div_score = self._diversification_score(
            weights=final_weights,
            risks=risks,
            portfolio_variance=portfolio_variance,
        )

        # ---- Sector exposure from actual allocated weights ----
        sector_exposure = self._compute_sector_exposure_from_allocations(
            allocations,
        )

        capital_used = sum(a.capital for a in allocations)
        cash_remaining = self._capital - capital_used

        # ---- Build result ----
        result = PortfolioOptimizationResult(
            method=method,
            expected_return=portfolio_return,
            portfolio_risk=portfolio_vol,
            sharpe_ratio=sharpe,
            diversification_score=div_score,
            capital_used=round(capital_used, 2),
            cash_remaining=round(cash_remaining, 2),
            allocations=allocations,
            weights={
                a.symbol: a.weight for a in allocations
            },
            sector_exposure=sector_exposure,
            summary=(
                f"Optimised {len(allocations)} positions using "
                f"'{method}' method — Sharpe: {sharpe:.4f}, "
                f"Risk: {portfolio_vol:.4f}, "
                f"Return: {portfolio_return:.4f}, "
                f"Capital used: NPR {capital_used:,.2f}"
            ),
            constraint_violations=violations,
        )

        # ---- Log completion ----
        logger.info(
            "Optimisation complete: method=%s, positions=%d, "
            "sharpe=%.4f, risk=%.4f, return=%.4f, "
            "capital_used=%.2f, cash_remaining=%.2f",
            method,
            len(allocations),
            sharpe,
            portfolio_vol,
            portfolio_return,
            capital_used,
            cash_remaining,
        )

        return result

    # ==================================================================
    # Internal — weight computation
    # ==================================================================

    def _compute_weights(
        self,
        method: str,
        expected_returns: list[float],
        risks: list[float],
        scores: list[float],
        confidences: list[float],
        correlation_matrix: list[list[float]] | None,
    ) -> list[float]:
        """Dispatch to the appropriate weight-computation method.

        Args:
            method: Optimisation method name.
            expected_returns: List of expected returns.
            risks: List of position risks (standard deviations).
            scores: List of recommendation scores.
            confidences: List of confidence values.
            correlation_matrix: Optional correlation matrix.

        Returns:
            List of raw weights (may sum to 1 or less).
        """
        n = len(expected_returns)

        if method == "equal_weight":
            return self._weights_equal_weight(n)

        elif method == "max_sharpe":
            if _HAS_SCIPY and _HAS_NUMPY:
                return self._weights_max_sharpe_scipy(
                    expected_returns, risks, correlation_matrix
                )
            logger.warning(
                "scipy/numpy not available — falling back to "
                "equal-weight for max_sharpe."
            )
            return self._weights_equal_weight(n)

        elif method == "min_variance":
            if _HAS_SCIPY and _HAS_NUMPY:
                return self._weights_min_variance_scipy(
                    risks, correlation_matrix
                )
            logger.warning(
                "scipy/numpy not available — falling back to "
                "equal-weight for min_variance."
            )
            return self._weights_equal_weight(n)

        elif method == "risk_parity":
            return self._weights_risk_parity(
                risks, correlation_matrix
            )

        elif method == "score_weighted":
            return self._weights_proportional(scores)

        elif method == "confidence_weighted":
            return self._weights_proportional(confidences)

        return self._weights_equal_weight(n)

    # ==================================================================
    # Internal — individual weight methods
    # ==================================================================

    @staticmethod
    def _weights_equal_weight(n: int) -> list[float]:
        """Compute equal weights for N positions.

        Args:
            n: Number of positions.

        Returns:
            List of equal weights summing to 1.
        """
        if n <= 0:
            return []
        weight = 1.0 / n
        return [weight] * n

    @staticmethod
    def _weights_proportional(values: list[float]) -> list[float]:
        """Compute weights proportional to a list of positive values.

        Args:
            values: List of numeric values (e.g. scores, confidences).

        Returns:
            Normalised weights summing to 1. Falls back to equal
            weights if all values are zero.
        """
        if not values:
            return []
        total = sum(max(v, 0.0) for v in values)
        if total <= 0:
            n = len(values)
            return [1.0 / n] * n
        return [max(v, 0.0) / total for v in values]

    def _weights_max_sharpe_scipy(
        self,
        expected_returns: list[float],
        risks: list[float],
        correlation_matrix: list[list[float]] | None,
    ) -> list[float]:
        """Maximise Sharpe ratio using scipy SLSQP.

        Args:
            expected_returns: List of expected returns.
            risks: List of standard deviations.
            correlation_matrix: Optional correlation matrix.

        Returns:
            Optimised weight vector.
        """
        n = len(expected_returns)
        cov_matrix = self._build_covariance_matrix(
            risks, correlation_matrix
        )

        # Objective: minimise negative Sharpe
        def _neg_sharpe(w: np.ndarray) -> float:  # type: ignore[no-untyped-def]
            ret = float(np.dot(w, expected_returns))
            var = float(w.T @ cov_matrix @ w)
            vol = math.sqrt(max(var, 1e-16))
            if vol == 0:
                return 0.0
            sharpe = (ret - self._risk_free_rate) / vol
            return -sharpe  # negate for minimisation

        return self._run_scipy_optimize(n, _neg_sharpe)

    def _weights_min_variance_scipy(
        self,
        risks: list[float],
        correlation_matrix: list[list[float]] | None,
    ) -> list[float]:
        """Minimise portfolio variance using scipy SLSQP.

        Args:
            risks: List of standard deviations.
            correlation_matrix: Optional correlation matrix.

        Returns:
            Optimised weight vector.
        """
        n = len(risks)
        cov_matrix = self._build_covariance_matrix(
            risks, correlation_matrix
        )

        def _variance(w: np.ndarray) -> float:  # type: ignore[no-untyped-def]
            return float(w.T @ cov_matrix @ w)

        return self._run_scipy_optimize(n, _variance)

    def _run_scipy_optimize(
        self,
        n: int,
        objective: Any,
    ) -> list[float]:
        """Run a scipy SLSQP optimisation with equality and bound constraints.

        Args:
            n: Number of assets.
            objective: Objective function to minimise.

        Returns:
            Optimised weight vector (list of floats).
        """
        # Initial guess: equal weight
        x0 = np.array([1.0 / n] * n, dtype=float)

        # Bounds: use (0, 1) here — let _apply_constraints handle
        # the min/max weight clamping after optimisation so that the
        # equality constraint (sum = 1) remains feasible.
        bounds = [(0.0, 1.0) for _ in range(n)]

        # Constraint: sum of weights = 1
        constraints = [
            {
                "type": "eq",
                "fun": lambda w: np.sum(w) - 1.0,
            }
        ]

        result = _scipy_minimize(
            objective,
            x0,
            method="SLSQP",
            bounds=bounds,
            constraints=constraints,
            tol=_SCIPY_TOL,
            options={"maxiter": _SCIPY_MAXITER},
        )

        if not result.success:
            logger.warning(
                "scipy optimisation did not converge: %s. "
                "Falling back to equal weight.",
                result.message,
            )
            return [1.0 / n] * n

        return result.x.tolist()

    def _weights_risk_parity(
        self,
        risks: list[float],
        correlation_matrix: list[list[float]] | None,
    ) -> list[float]:
        """Compute risk-parity weights using an iterative algorithm.

        Uses the coordinate-descent approach to equalise risk
        contributions from each position.

        Args:
            risks: List of standard deviations.
            correlation_matrix: Optional correlation matrix.

        Returns:
            Risk-parity weight vector.
        """
        n = len(risks)
        if n <= 1:
            return [1.0] if n == 1 else []

        # Use scipy if available for a more accurate solution
        if _HAS_SCIPY and _HAS_NUMPY:
            cov_matrix = self._build_covariance_matrix(
                risks, correlation_matrix
            )

            def _risk_parity_objective(w: np.ndarray) -> float:  # type: ignore[no-untyped-def]
                portfolio_var = float(w.T @ cov_matrix @ w)
                if portfolio_var <= 0:
                    return 0.0
                # Marginal risk contributions
                mrc = (cov_matrix @ w).tolist()
                # Risk contributions
                rc = [float(w[i] * mrc[i]) for i in range(n)]
                # Objective: sum of squared differences between RC pairs
                objective = 0.0
                for i in range(n):
                    for j in range(i + 1, n):
                        objective += (rc[i] - rc[j]) ** 2
                return objective

            return self._run_scipy_optimize(n, _risk_parity_objective)

        # Fallback: iterative coordinate descent (no scipy)
        weights = [1.0 / n] * n
        corr = correlation_matrix or self._default_correlation_matrix(
            n
        )
        max_iter = 100
        tol = 1e-6

        for _ in range(max_iter):
            # Compute marginal risk contributions
            portfolio_var = self._portfolio_variance(
                weights, risks, corr
            )
            if portfolio_var <= 0:
                break

            mrc = self._marginal_risk_contributions(
                weights, risks, corr
            )
            rc = [weights[i] * mrc[i] for i in range(n)]
            avg_rc = sum(rc) / n

            # Adjust weights
            new_weights = [
                max(
                    self._min_weight,
                    min(
                        self._max_weight,
                        weights[i] * (avg_rc / max(rc[i], 1e-16)),
                    ),
                )
                for i in range(n)
            ]

            # Normalise
            total = sum(new_weights)
            if total > 0:
                new_weights = [w / total for w in new_weights]

            # Check convergence
            diff = sum(
                abs(new_weights[i] - weights[i]) for i in range(n)
            )
            weights = new_weights
            if diff < tol:
                break

        return weights

    # ==================================================================
    # Internal — constraint enforcement
    # ==================================================================

    def _apply_constraints(
        self,
        weights: list[float],
        sectors: list[str],
    ) -> list[float]:
        """Apply position weight and sector constraints.

        Enforces min/max per-position weights and sector exposure
        limits iteratively.

        Sector weights are only reduced when the accumulated exposure
        for that sector would exceed the configured limit; otherwise
        the original weights are preserved exactly.

        All sector weight arithmetic uses ``round(..., 10)`` to
        prevent floating-point drift (e.g. ``0.30000000000000004``).

        Args:
            weights: Raw weight vector.
            sectors: Sector labels for each position.

        Returns:
            Constrained weight vector.
        """
        n = len(weights)
        constrained = list(weights)

        # 1. Clamp individual weights to [min_weight, max_weight]
        for i in range(n):
            constrained[i] = max(
                self._min_weight,
                min(self._max_weight, constrained[i]),
            )

        # 2. Enforce sector limits — only clamp when the limit would
        #    actually be exceeded.  Otherwise preserve the ideal weight.
        sector_weight: dict[str, float] = {}
        for i, sector in enumerate(sectors):
            cur = sector_weight.get(sector, 0.0)
            if cur + constrained[i] > self._sector_limit:
                # Cap this position so the sector fills exactly to the limit
                constrained[i] = max(
                    0.0,
                    round(self._sector_limit - cur, 10),
                )
            # Always track the running sector total with rounding
            sector_weight[sector] = round(
                sector_weight.get(sector, 0.0) + constrained[i],
                10,
            )

        # 3. Normalise to sum to 1 only when weights exceed 100%
        # (clamping can push individual weights down, and we want to
        #  leave cash on the side rather than re-leveraging).
        total = sum(constrained)
        if total > 1.0:
            constrained = [w / total for w in constrained]

        return constrained

    def _check_sector_limits(
        self,
        weights: list[float],
        sectors: list[str],
        symbols: list[str],
    ) -> list[str]:
        """Check whether any sector exceeds the configured limit.

        Args:
            weights: Final weight vector.
            sectors: Sector labels for each position.
            symbols: Symbol names for reporting.

        Returns:
            List of violation messages (empty if none).
        """
        violations: list[str] = []
        sector_exposure: dict[str, float] = {}
        for i, sector in enumerate(sectors):
            sector_exposure[sector] = (
                sector_exposure.get(sector, 0.0) + weights[i]
            )

        for sector, exposure in sector_exposure.items():
            if exposure > self._sector_limit:
                violations.append(
                    f"Sector '{sector}' exposure {exposure:.4f} "
                    f"exceeds limit {self._sector_limit:.4f}."
                )

        return violations

    # ==================================================================
    # Internal — allocation building
    # ==================================================================

    def _build_allocations(
        self,
        symbols: list[str],
        weights: list[float],
        expected_returns: list[float],
        risks: list[float],
        sectors: list[str],
        prices: list[float] | None = None,
    ) -> list[PortfolioAllocation]:
        """Build PortfolioAllocation objects from weights and metadata.

        Share counts are computed from the position capital divided by
        the actual price per share.  When price data is unavailable (0
        or missing), shares default to the integer floor of the capital
        amount.

        Args:
            symbols: List of ticker symbols.
            weights: List of portfolio weights.
            expected_returns: List of expected returns.
            risks: List of position risks.
            sectors: List of sector labels.
            prices: Optional list of per-share prices for share
                calculation.  Missing or zero prices are substituted
                with 1.0 so that capital ≈ shares.

        Returns:
            List of :class:`PortfolioAllocation` instances.
        """
        allocations: list[PortfolioAllocation] = []
        prices = prices or []
        for i, symbol in enumerate(symbols):
            # Defensive clamp: enforce min/max position weight even if the
            # upstream constraint pipeline was bypassed or failed.
            raw_weight = weights[i]
            weight = max(
                self._min_weight,
                min(self._max_weight, raw_weight),
            )
            capital = self._capital * weight
            price = prices[i] if i < len(prices) and prices[i] > 0 else 1.0
            shares = int(capital / max(price, 1.0))
            actual_capital = shares * price

            allocations.append(
                PortfolioAllocation(
                    symbol=symbol,
                    weight=weight,
                    shares=shares,
                    capital=round(actual_capital, 2),
                    expected_return=expected_returns[i],
                    risk=risks[i],
                    sector=sectors[i],
                )
            )

        return allocations

    # ==================================================================
    # Internal — portfolio metrics
    # ==================================================================

    @staticmethod
    def _portfolio_return(
        weights: list[float],
        expected_returns: list[float],
    ) -> float:
        """Compute the weighted portfolio return.

        Args:
            weights: Portfolio weights.
            expected_returns: Per-position expected returns.

        Returns:
            Weighted average return.
        """
        if not weights or not expected_returns:
            return 0.0
        return sum(
            w * r for w, r in zip(weights, expected_returns)
        )

    def _portfolio_variance(
        self,
        weights: list[float],
        risks: list[float],
        correlation_matrix: list[list[float]] | None,
    ) -> float:
        """Compute the portfolio variance.

        If a correlation matrix is provided, uses it.  Otherwise falls
        back to an independent-asset assumption with a default pairwise
        correlation.

        Args:
            weights: Portfolio weights.
            risks: Per-position standard deviations.
            correlation_matrix: Optional NxN correlation matrix.

        Returns:
            Portfolio variance.
        """
        n = len(weights)
        if n == 0:
            return 0.0

        if n == 1:
            return risks[0] ** 2 if risks else 0.0

        corr = correlation_matrix or self._default_correlation_matrix(
            n
        )

        var = 0.0
        for i in range(n):
            for j in range(n):
                ci = corr[i][j] if i < len(corr) and j < len(
                    corr[i]
                ) else _DEFAULT_CORRELATION
                var += (
                    weights[i]
                    * weights[j]
                    * risks[i]
                    * risks[j]
                    * ci
                )

        return var

    def _marginal_risk_contributions(
        self,
        weights: list[float],
        risks: list[float],
        correlation_matrix: list[list[float]],
    ) -> list[float]:
        """Compute marginal risk contributions for each position.

        MRC_i = (cov_matrix @ weights)_i / portfolio_vol

        Args:
            weights: Portfolio weights.
            risks: Per-position standard deviations.
            correlation_matrix: NxN correlation matrix.

        Returns:
            List of marginal risk contributions.
        """
        n = len(weights)
        port_var = self._portfolio_variance(
            weights, risks, correlation_matrix
        )
        port_vol = math.sqrt(max(port_var, 1e-16))

        mrc: list[float] = []
        for i in range(n):
            cov_sum = 0.0
            for j in range(n):
                ci = correlation_matrix[i][j] if i < len(
                    correlation_matrix
                ) and j < len(correlation_matrix[i]) else _DEFAULT_CORRELATION
                cov_sum += weights[j] * risks[i] * risks[j] * ci
            mrc.append(cov_sum / port_vol)

        return mrc

    def _sharpe_ratio(
        self,
        portfolio_return: float,
        portfolio_vol: float,
    ) -> float:
        """Compute the Sharpe ratio.

        Args:
            portfolio_return: Expected portfolio return.
            portfolio_vol: Portfolio volatility (standard deviation).

        Returns:
            Sharpe ratio, or ``0.0`` if volatility is zero.
        """
        if portfolio_vol <= 0:
            return 0.0
        if portfolio_return - self._risk_free_rate <= 0:
            return 0.0
        return (
            portfolio_return - self._risk_free_rate
        ) / portfolio_vol

    @staticmethod
    def _diversification_score(
        weights: list[float],
        risks: list[float],
        portfolio_variance: float,
    ) -> float:
        """Compute the diversification score.

        A portfolio with only one position is not diversified — the
        score is always ``0.0`` in that case.

        For multi-position portfolios the formula is:
            score = 1 - (sum(w_i^2 * sigma_i^2) / var_portfolio)

        A score of 0 = no diversification (single stock equivalent).
        A score approaching 1 = highly diversified.

        Args:
            weights: Portfolio weights.
            risks: Per-position standard deviations.
            portfolio_variance: Total portfolio variance.

        Returns:
            Diversification score in [0, 1].
        """
        # Single position → not diversified
        if len(weights) <= 1:
            return 0.0

        if portfolio_variance <= 0:
            return 0.0

        numerator = sum(
            (w ** 2) * (r ** 2)
            for w, r in zip(weights, risks)
        )

        if numerator <= 0:
            return 0.0

        score = 1.0 - (numerator / portfolio_variance)
        return max(0.0, min(1.0, score))

    @staticmethod
    def _compute_sector_exposure(
        weights: list[float],
        sectors: list[str],
    ) -> dict[str, float]:
        """Compute total exposure per sector.

        Args:
            weights: Portfolio weights.
            sectors: Sector labels for each position.

        Returns:
            Dictionary mapping sector names to total weight.
        """
        exposure: dict[str, float] = {}
        for w, sector in zip(weights, sectors):
            exposure[sector] = exposure.get(sector, 0.0) + w

        # Ensure all categories appear
        for category in _SECTOR_CATEGORIES:
            if category not in exposure:
                exposure[category] = 0.0

        return exposure

    @staticmethod
    def _compute_sector_exposure_from_allocations(
        allocations: list[PortfolioAllocation],
    ) -> dict[str, float]:
        """Compute sector exposure from the final allocation objects.

        Uses the actual ``.weight`` and ``.sector`` fields on each
        :class:`PortfolioAllocation`, which reflect any clamping that
        happened during allocation building.

        Args:
            allocations: List of final :class:`PortfolioAllocation`
                instances.

        Returns:
            Dictionary mapping sector names to total allocated weight.
        """
        exposure: dict[str, float] = {}
        for alloc in allocations:
            exposure[alloc.sector] = (
                exposure.get(alloc.sector, 0.0) + alloc.weight
            )
        # Ensure all categories appear
        for category in _SECTOR_CATEGORIES:
            if category not in exposure:
                exposure[category] = 0.0
        return exposure

    # ==================================================================
    # Internal — correlation / covariance helpers
    # ==================================================================

    @staticmethod
    def _default_correlation_matrix(
        n: int,
    ) -> list[list[float]]:
        """Build a default correlation matrix with uniform pairwise correlation.

        Uses ``_DEFAULT_CORRELATION`` (0.15) for off-diagonal entries
        and 1.0 on the diagonal.

        Args:
            n: Size of the matrix.

        Returns:
            NxN correlation matrix as a list of lists.
        """
        matrix: list[list[float]] = []
        for i in range(n):
            row: list[float] = []
            for j in range(n):
                row.append(1.0 if i == j else _DEFAULT_CORRELATION)
            matrix.append(row)
        return matrix

    @staticmethod
    def _build_covariance_matrix(
        risks: list[float],
        correlation_matrix: list[list[float]] | None,
    ) -> Any:
        """Build a covariance matrix from risks and correlation.

        Uses numpy when available for efficient construction.

        Args:
            risks: List of standard deviations.
            correlation_matrix: Optional NxN correlation matrix.

        Returns:
            Covariance matrix as a numpy array (if available) or
            list of lists.
        """
        n = len(risks)
        corr = correlation_matrix or PortfolioOptimizer._default_correlation_matrix(
            n
        )

        if _HAS_NUMPY:
            corr_arr = np.array(corr, dtype=float)
            std_arr = np.array(risks, dtype=float)
            return np.outer(std_arr, std_arr) * corr_arr

        # Fallback: pure Python
        cov: list[list[float]] = []
        for i in range(n):
            row: list[float] = []
            for j in range(n):
                c = corr[i][j] if i < len(corr) and j < len(
                    corr[i]
                ) else _DEFAULT_CORRELATION
                row.append(risks[i] * risks[j] * c)
            cov.append(row)
        return cov

    # ==================================================================
    # Internal — recommendation parsing
    # ==================================================================

    @staticmethod
    def extract_from_trade_recommendation(
        recommendation: Any,
    ) -> dict[str, Any]:
        """Convert a ``TradeRecommendation`` to a standard dict.

        Works with :class:`~src.recommendations.engine.TradeRecommendation`
        or any object that has ``symbol``, ``signal``, ``confidence``,
        ``average_score``, ``entry_price`` attributes.

        Args:
            recommendation: A TradeRecommendation or compatible object.

        Returns:
            Dict with keys: ``symbol``, ``confidence``, ``score``,
            ``expected_return``, ``risk``, ``sector``, ``signal``,
            ``price``.
        """
        return {
            "symbol": getattr(recommendation, "symbol", ""),
            "signal": getattr(recommendation, "signal", "HOLD"),
            "confidence": float(
                getattr(recommendation, "confidence", 0.0)
            ),
            "score": float(
                getattr(recommendation, "average_score", 0.0)
            ),
            "expected_return": float(
                getattr(recommendation, "expected_return", 0.0)
            ),
            "risk": float(getattr(recommendation, "risk", 0.0)),
            "sector": str(
                getattr(recommendation, "sector", "Others")
            ),
            "price": (
                float(getattr(recommendation, "entry_price", 0.0))
                if getattr(recommendation, "entry_price", None)
                is not None
                else 0.0
            ),
        }

    # ==================================================================
    # Internal — recommendation filtering
    # ==================================================================

    def _filter_recommendations(
        self,
        recommendations: list[dict[str, Any]],
        max_positions: int,
        min_confidence: float,
        min_score: float,
    ) -> list[dict[str, Any]]:
        """Filter and sort recommendations.

        Keeps only BUY signals, enforces minimum confidence and score
        thresholds, caps the number of positions, and sorts by score
        descending.

        Args:
            recommendations: Raw recommendation list.
            max_positions: Maximum number of positions.
            min_confidence: Minimum confidence (0–100).
            min_score: Minimum score.

        Returns:
            Filtered and sorted recommendation list.
        """
        # Parse recommendations from possible TradeRecommendation objs
        parsed: list[dict[str, Any]] = []
        for rec in recommendations:
            if isinstance(rec, dict):
                parsed.append(rec)
            else:
                parsed.append(
                    self.extract_from_trade_recommendation(rec)
                )

        # Filter: only BUY signals with valid symbols
        filtered = [
            r
            for r in parsed
            if r.get("signal", "HOLD").upper().strip() == "BUY"
            and r.get("symbol")
        ]

        # Apply confidence threshold
        if min_confidence > 0:
            filtered = [
                r
                for r in filtered
                if float(r.get("confidence", 0.0)) >= min_confidence
            ]

        # Apply score threshold
        if min_score > 0:
            filtered = [
                r
                for r in filtered
                if float(r.get("score", 0.0)) >= min_score
            ]

        # Sort by score descending
        filtered.sort(
            key=lambda r: float(r.get("score", 0.0)),
            reverse=True,
        )

        # Cap positions
        if max_positions > 0:
            filtered = filtered[:max_positions]

        return filtered

    # ==================================================================
    # Internal — validation
    # ==================================================================

    @staticmethod
    def _validate_correlation_matrix(
        correlation_matrix: list[list[float]] | None,
        expected_size: int,
    ) -> None:
        """Validate an optional correlation matrix.

        Args:
            correlation_matrix: The matrix to validate, or None.
            expected_size: Expected number of rows/cols.

        Raises:
            ValueError: If the matrix is invalid.
        """
        if correlation_matrix is None:
            return

        if not isinstance(correlation_matrix, list):
            raise ValueError(
                "correlation_matrix must be a list of lists."
            )

        n = len(correlation_matrix)
        if n != expected_size:
            raise ValueError(
                f"correlation_matrix size ({n}) does not match "
                f"number of recommendations ({expected_size})."
            )

        for i, row in enumerate(correlation_matrix):
            if not isinstance(row, list):
                raise ValueError(
                    f"Row {i} of correlation_matrix is not a list."
                )
            if len(row) != expected_size:
                raise ValueError(
                    f"Row {i} of correlation_matrix has length "
                    f"{len(row)}, expected {expected_size}."
                )
            for j, val in enumerate(row):
                if not isinstance(val, (int, float)):
                    raise ValueError(
                        f"correlation_matrix[{i}][{j}] is not a "
                        f"number, got {type(val).__name__}."
                    )
                if val < -1.0 or val > 1.0:
                    raise ValueError(
                        f"correlation_matrix[{i}][{j}] = {val} "
                        f"is outside [-1, 1]."
                    )

    # ==================================================================
    # Property accessors (for testing)
    # ==================================================================

    @property
    def risk_free_rate(self) -> float:
        """Return the configured risk-free rate."""
        return self._risk_free_rate
