"""Alerts page — monitor and manage live trading alerts generated by the scanner."""

from __future__ import annotations

from typing import Any

import streamlit as st
import pandas as pd

from src.ui.components import kpi_card
from src.ui.helpers import (
    section_header,
    divider,
    fmt_rupees,
    fmt_pct,
    safe_get,
    safe_float,
    fmt_number,
)
from src.ui.state import should_refresh, touch_cache
from src.data import DataService as _DataService
from src.ui.notifications import notification_manager as _notif, render_notification_drawer


def _svc() -> _DataService:
    return _DataService()


def render() -> None:
    """Render the unified Notification Center."""
    section_header("🔔 Notification Center", "Unified trading alerts, system notifications, and event history")

    # ── Tabs: All | Categories ───────────────────────────────────
    tab_all, tab_portfolio, tab_scanner, tab_price, tab_market, tab_system, tab_trade = st.tabs([
        "📋 All", "💼 Portfolio", "🔍 Scanner", "💰 Price", "📊 Market", "⚙️ System", "📝 Trades",
    ])

    with tab_all:
        render_notification_drawer()

    with tab_portfolio:
        notifs = _notif.get_by_category("portfolio")
        if notifs:
            _render_notif_list(notifs)
        else:
            st.info("No portfolio notifications")
    with tab_scanner:
        notifs = _notif.get_by_category("scanner")
        if notifs:
            _render_notif_list(notifs)
        else:
            st.info("No scanner notifications")
    with tab_price:
        notifs = _notif.get_by_category("price")
        if notifs:
            _render_notif_list(notifs)
        else:
            st.info("No price notifications")
    with tab_market:
        notifs = _notif.get_by_category("market")
        if notifs:
            _render_notif_list(notifs)
        else:
            st.info("No market notifications")
    with tab_system:
        notifs = _notif.get_by_category("system")
        if notifs:
            _render_notif_list(notifs)
        else:
            st.info("No system notifications")
    with tab_trade:
        notifs = _notif.get_by_category("trade")
        if notifs:
            _render_notif_list(notifs)
        else:
            st.info("No trade notifications")

    # ── Search ──────────────────────────────────────────────────
    divider()
    with st.expander("🔍 Search Notifications", expanded=False):
        search_q = st.text_input("Search", placeholder="Search title, message, or symbol...", key="notif_search")
        if search_q:
            results = _notif.search(search_q)
            if results:
                _render_notif_list(results)
            else:
                st.info("No matching notifications")


def _render_notif_list(notifications: list) -> None:
    """Render a list of notifications with mark-read and dismiss buttons."""
    from src.ui.theme import theme as t
    color_map = {"success": t.success, "warning": t.warning, "critical": t.danger, "info": t.info}
    icon_map = {"portfolio": "💼", "scanner": "🔍", "price": "💰",
                 "market": "📊", "websocket": "📡", "system": "⚙️",
                 "background": "🔄", "trade": "📝"}

    for n in notifications[:20]:
        c = color_map.get(n.priority, t.text_secondary)
        icon = icon_map.get(n.category, "📌")
        col1, col2, col3 = st.columns([5, 1, 1])
        with col1:
            st.markdown(
                f"""<div style="
                    background: {'#1E2128' if not n.read else '#161A20'};
                    border-left: 3px solid {c};
                    border-radius: 4px; padding: 8px 12px;
                    margin-bottom: 4px;
                ">
                    <div style="display: flex; justify-content: space-between;">
                        <span style="color: {t.text};">
                            {icon} <strong>{n.title}</strong>
                            {f'<span style="color: {c};"> ({n.symbol})</span>' if n.symbol else ''}
                        </span>
                        <span style="color: {t.text_muted}; font-size: 0.75rem;">{n.timestamp[11:19] if n.timestamp else ''}</span>
                    </div>
                    <p style="color: {t.text_secondary}; font-size: 0.85rem; margin: 2px 0 0;">{n.message}</p>
                </div>""",
                unsafe_allow_html=True,
            )
        with col2:
            if not n.read and st.button("✓", key=f"read_{n.id}", use_container_width=True):
                _notif.mark_read(n.id)
                st.rerun()
        with col3:
            if st.button("✕", key=f"dismiss_{n.id}", use_container_width=True):
                _notif.dismiss(n.id)
                st.rerun()

    if len(notifications) > 20:
        st.caption(f"Showing 20 of {len(notifications)} notifications")

# DEPRECATED: Legacy alert loader. Kept for backward compatibility — delegates to NotificationManager.
def _load_alerts(force_refresh: bool = False) -> list[dict[str, Any]]:
    """Legacy alert loader.

    Delegates to NotificationManager.  The *force_refresh* parameter
    is accepted for backward compatibility but ignored (the manager
    persists history internally).
    """
    from src.ui.notifications import NotificationManager
    mgr = NotificationManager()
    return [{"date": n.timestamp, "symbol": n.symbol, "type": n.priority, "message": n.title}
            for n in mgr.get_all(limit=200)]
