"""Recommendations page — display trade recommendations in a table."""

from __future__ import annotations

from src.ui.helpers import (
    display_data_table,
    display_error_message,
    display_info_message,
    format_percent,
    format_number,
    format_currency,
)
from src.ui.state import get_state, set_state
from src.logging.logger import logger


def render_recommendations_page() -> None:
    """Render the recommendations page."""
    import streamlit as st

    st.header("💡 Recommendations")
    st.markdown("Trade recommendations generated by the Quant Engine.")

    results = get_state("watchlist_results", [])

    if not results:
        display_info_message(
            "No recommendations available. "
            "Run a **Market Scan** first or configure the watchlist."
        )

        # Manual recommendation input
        st.subheader("Generate Recommendation for a Symbol")
        symbol = st.text_input("Symbol", placeholder="e.g. NABIL").strip().upper()
        if symbol and st.button("Recommend", type="primary"):
            with st.spinner(f"Generating recommendation for {symbol}..."):
                try:
                    from src.recommendations.engine import RecommendationEngine
                    from src.config import DATA_DIRECTORY
                    from pathlib import Path
                    import pandas as pd

                    data_path = Path(DATA_DIRECTORY) / f"{symbol.lower()}.csv"
                    if not data_path.exists():
                        display_error_message(f"No data for '{symbol}'.")
                        return

                    df = pd.read_csv(str(data_path))
                    engine = RecommendationEngine(capital=get_state("capital", 1_000_000.0))
                    rec = engine.recommend(symbol, df)

                    st.subheader(f"Recommendation: {symbol}")
                    col1, col2, col3 = st.columns(3)
                    col1.metric("Signal", rec.signal)
                    col2.metric("Confidence", format_percent(rec.confidence / 100))
                    col3.metric("Score", format_number(rec.average_score, 2))

                    if rec.signal == "BUY":
                        details = [
                            {"Metric": "Entry Price", "Value": format_currency(rec.entry_price or 0)},
                            {"Metric": "Stop Loss", "Value": format_currency(rec.stop_loss or 0)},
                            {"Metric": "Position Size", "Value": f"{rec.shares} shares"},
                            {"Metric": "Position Value", "Value": format_currency(rec.position_value)},
                            {"Metric": "Capital at Risk", "Value": format_currency(rec.capital_at_risk)},
                            {"Metric": "Portfolio Weight", "Value": format_percent(rec.portfolio_weight)},
                        ]
                        display_data_table(details)

                    if rec.reasons:
                        st.subheader("Reasons")
                        for r in rec.reasons:
                            st.markdown(f"- {r}")

                except Exception as exc:
                    logger.exception("Recommendation failed: %s", exc)
                    display_error_message(f"Error: {exc}")
        return

    # Display cached recommendations
    st.subheader(f"Latest Recommendations ({len(results)} signals)")
    table = []
    for r in results:
        table.append({
            "Symbol": r.get("symbol", ""),
            "Signal": r.get("signal", "HOLD"),
            "Confidence": format_percent(r.get("confidence", 0.0) / 100),
            "Score": format_number(r.get("score", 0.0), 1),
            "Position Size": str(r.get("shares", 0)),
            "Risk": format_percent(r.get("risk", 0.0)),
            "Expected Return": format_percent(r.get("expected_return", 0.0)),
            "Reason": r.get("reason", ""),
        })
    display_data_table(table)

    logger.info("Recommendations page rendered.")
