"""Persistent-state inventory (Sprint 13.9 §12).

A single source of truth describing every durable store the platform
writes, so operators and tooling can reason about location, format,
versioning, atomicity, locking, corruption behaviour, backup and
migration without reading every module.

This is **metadata only** — it creates no state store, writes no files,
and must never be treated as a store itself.  ``STATE_STORES`` is a
frozen, ordered tuple; tests assert it stays accurate (every JSON store
in the platform routes through ``src.utils.json_store``, every entry's
owner module imports, etc.).

The human-readable mirror lives in ``docs/STATE_INVENTORY.md``.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class StateStore:
    """One durable store and its operational contract."""

    name: str
    owner: str            # module that owns the store
    location: str         # path template; {NEPSE_HOME} expands at runtime
    store_format: str     # json | csv | sqlite | text
    versioned: bool       # in-file schema version tracked & enforced
    atomic_writes: bool   # temp-file + os.replace
    cross_process_lock: bool  # json_store cross-process lock
    corruption_policy: str    # what happens on a damaged file
    backup: str               # mechanism that backs this store up
    migration: str            # versioned migration / none required
    rollback: str             # how an operator rolls this store back
    bounded: bool             # growth is bounded


# ``{NEPSE_HOME}`` expands to ``$NEPSE_HOME`` or ``~/.nepse``
# (src/data/cache.py, src/trading/journal.py, src/portfolio/database.py,
# src/alerts/center.py).
STATE_STORES: tuple[StateStore, ...] = (
    StateStore(
        name="Trading calendar",
        owner="src/data/calendar.py",
        location="data/state/nepse_calendar.json",
        store_format="json",
        versioned=True,  # schema 1.0 / 2.0, SUPPORTED_CALENDAR_VERSIONS
        atomic_writes=True,
        cross_process_lock=True,  # activation + history via json_store
        corruption_policy="backup-aside + validated default (base weekend rule)",
        backup="calendar backups (*.bak.json) + version history",
        migration="versioned; unsupported versions rejected, never silently reinterpreted",
        rollback="rollback_calendar() restores last valid backup with validation",
        bounded=True,
    ),
    StateStore(
        name="Calendar version history",
        owner="src/data/calendar.py",
        location="data/state/nepse_calendar_history.json",
        store_format="json",
        versioned=False,
        atomic_writes=True,
        cross_process_lock=True,  # update_json
        corruption_policy="backup-aside + empty history default",
        backup="shipped inside calendar backup cycle",
        migration="none required (bounded list of {version, timestamp})",
        rollback="rebuilt on next activation",
        bounded=True,  # CALENDAR_MAX_HISTORY
    ),
    StateStore(
        name="Watchlist",
        owner="src/watchlist/manager.py",
        location="data/watchlist/watchlist.json",
        store_format="json",
        versioned=False,
        atomic_writes=True,
        cross_process_lock=True,  # update_json
        corruption_policy="backup-aside + empty watchlist default",
        backup="scripts/backup.sh (data/)",
        migration="none required; wrong-shape file falls back to {}",
        rollback="scripts/restore.sh",
        bounded=True,  # bounded by symbol set
    ),
    StateStore(
        name="Alert history",
        owner="src/alerts/history.py",
        location="data/alerts/history.json",
        store_format="json",
        versioned=False,
        atomic_writes=True,
        cross_process_lock=True,  # update_json
        corruption_policy="backup-aside + empty history default",
        backup="scripts/backup.sh (data/)",
        migration="none required; wrong-shape file falls back to {}",
        rollback="scripts/restore.sh",
        bounded=True,  # per-symbol milestone map
    ),
    StateStore(
        name="Worker metrics",
        owner="src/utils/worker_metrics.py",
        location="data/state/worker_metrics.json",
        store_format="json",
        versioned=False,
        atomic_writes=True,
        cross_process_lock=True,  # update_json
        corruption_policy="backup-aside + tolerated (best-effort observability)",
        backup="scripts/backup.sh (data/)",
        migration="none required; stale records TTL-pruned",
        rollback="regenerated by workers",
        bounded=True,  # WORKER_METRICS_TTL_S prunes inactive records
    ),
    StateStore(
        name="Disk cache",
        owner="src/data/cache.py",
        location="{NEPSE_HOME}/cache",
        store_format="json",
        versioned=False,
        atomic_writes=True,  # save_json per entry
        cross_process_lock=False,  # last-writer-wins idempotent entries
        corruption_policy="read failure = cache miss (never crashes caller)",
        backup="scripts/backup.sh (nepse_home)",
        migration="none required; cache is disposable",
        rollback="clear cache directory",
        bounded=True,  # TTL expiry + per-entry size
    ),
    StateStore(
        name="Trade journal",
        owner="src/trading/journal.py",
        location="{NEPSE_HOME}/journal",
        store_format="json",
        versioned=False,
        atomic_writes=True,
        cross_process_lock=True,
        corruption_policy="backup-aside + default",
        backup="scripts/backup.sh (nepse_home)",
        migration="none required",
        rollback="scripts/restore.sh",
        bounded=True,
    ),
    StateStore(
        name="Alert rules / center",
        owner="src/alerts/center.py",
        location="{NEPSE_HOME}/alerts.json",
        store_format="json",
        versioned=False,
        atomic_writes=True,
        cross_process_lock=True,
        corruption_policy="backup-aside + default",
        backup="scripts/backup.sh (nepse_home)",
        migration="none required",
        rollback="scripts/restore.sh",
        bounded=True,
    ),
    StateStore(
        name="Portfolio database",
        owner="src/portfolio/database.py",
        location="{NEPSE_HOME}/portfolio.db",
        store_format="sqlite",
        versioned=False,
        atomic_writes=True,  # SQLite transactions
        cross_process_lock=True,  # SQLite locking
        corruption_policy="transaction journal; corrupt db recreated empty",
        backup="scripts/backup.sh (nepse_home)",
        migration="none required",
        rollback="scripts/restore.sh",
        bounded=True,
    ),
    StateStore(
        name="Market corpus",
        owner="src/loaders + scripts/refresh_corpus.py",
        location="data/raw/*.csv",
        store_format="csv",
        versioned=False,
        atomic_writes=True,  # corpus refresh writes via temp+replace
        cross_process_lock=False,
        corruption_policy="record-level validation rejects bad rows",
        backup="scripts/backup.sh (data/)",
        migration="none required",
        rollback="scripts/restore.sh",
        bounded=True,  # operator-managed corpus
    ),
    StateStore(
        name="Release manifest",
        owner="src/utils/release_manifest.py",
        location="data/state/release_manifest.json",
        store_format="json",
        versioned=True,  # manifest schema version
        atomic_writes=True,
        cross_process_lock=False,  # build-time artifact, single writer
        corruption_policy="regenerate from scripts/build_release_manifest.py",
        backup="regenerated, not backed up (no secrets, no state)",
        migration="schema-versioned manifest",
        rollback="regenerate previous version",
        bounded=True,  # single fixed-size file
    ),
)


def store_names() -> list[str]:
    """Names of every registered store (deterministic order)."""
    return [store.name for store in STATE_STORES]


def store_by_name(name: str) -> StateStore | None:
    """Return the store with *name*, or ``None``."""
    for store in STATE_STORES:
        if store.name == name:
            return store
    return None


def json_stores() -> list[StateStore]:
    """Every registered JSON store (used by the corruption matrix tests)."""
    return [s for s in STATE_STORES if s.store_format == "json"]


__all__ = ["StateStore", "STATE_STORES", "store_names", "store_by_name", "json_stores"]
